### ISSUE TITLE
[Suggestion]: Compatibility with Iron's Spells 'n Spellbooks

### ISSUE THREAD

**Issue by akera099** [StudioBreadworks/Sorcerium#17]
### Your Name

Akera

### What is your suggestion?

[Iron's Spells 'n Spellbooks](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks) is a magic mod that is inspired by classic RPG games, and aims to introduce the classic spellcasting fantasy to the game. With an emphasis on progression, you can gain power by fighting dangerous wizards, raiding a plethora of structures, delving through dungeons, collecting resources, and finding powerful magical items.

It adds a mana system, akin to that of Sorcerium. It would be nice it both systems could use the same mana bar, since both mods are quite complementary. Sorcerium focuses on staves while Iron's adds mainly spellbooks and scrolls. They both make a fine addition, but the two mana systems are both independant. Considering that Ars Nouveau is also hugely popular, that makes up to 3 different mana bars for a magic focused modpack.

**Comment by Minebrah** [comment]
ditto :)
